//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.09 at 07:04:01 PM CDT 
//


package com.ipartek.formacion.web_service_soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alumnoInfo" type="{http://formacion.ipartek.com/web-service-soap}alumnoInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alumnoInfo"
})
@XmlRootElement(name = "getAlumnoResponse")
public class GetAlumnoResponse {

    @XmlElement(required = true)
    protected AlumnoInfo alumnoInfo;

    /**
     * Gets the value of the alumnoInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AlumnoInfo }
     *     
     */
    public AlumnoInfo getAlumnoInfo() {
        return alumnoInfo;
    }

    /**
     * Sets the value of the alumnoInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlumnoInfo }
     *     
     */
    public void setAlumnoInfo(AlumnoInfo value) {
        this.alumnoInfo = value;
    }

}
