//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.09 at 07:04:01 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://formacion.ipartek.com/web-service-soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ipartek.formacion.web_service_soap;
